# Generated by Django 4.0.6 on 2022-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquileres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_operacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad_ambientes', models.IntegerField()),
                ('cantidad_dormitorios', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_operacion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad_ambientes', models.IntegerField()),
                ('cantidad_dormitorios', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
